### ISSUE TITLE
Question about the script?

### ISSUE THREAD

**Issue by cyb3rgh05t** [KBlixt/PlexDatabaseEditor#4]
hi,

i want to say thanks for this amazing script :)

Will it be possible to make this happen also for TVShows and maybe for other movies section ids?

thanks

**Comment by KBlixt** [comment]
Thanks I'm glad you're enjoying it :)

Yepp that would be possible. For TV-shows I can't see how useful it would be though since TV-shows is less in need for discovering. At least for me.

And as for other movie sections I guess you could just run the script from different folders since it just uses the config file that is in the same folder that the script is in. I could probably adapt the script to run through multiple libraries but as far as I'm aware the "recently added movies" is not library specific. 

I'll probably revisit the script in the future sometime and when I do I'll keep these ideas in mind.

**Comment by keldian** [comment]
Kudos of course for this project. Discovery aside, the reason you may want to add support for TV shows is to allow people to fix such issues as [this one](https://forums.plex.tv/t/individual-seasons-episodes-showing-up-in-recently-added-tv/225039), by setting all the episodes of the same season to the same added_at value, so that they show up in "Recently Added TV" as a single item. This is the only script I could find that already has the groundwork laid out for that sort of thing.

**Comment by KBlixt** [comment]
Thank you very much 😀

Yupp, that makes sense. I'll give it a peek later today and see if I can add this. 

I'm a bit unsure of the behaviour of the recently added TV shows tab. If you have any insights into this that would help.

When do plex put the entire show there as one item? 

My initial solution would be to put the entire show as added to the same as the latest episode got released. 
Is there any other "priority" that would be convenient/useful? Maybe try to keep the order of recently added. Just update the added at data but keeping them in the same order.
